//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson_4.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int CourseStreamID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual CourseStream CourseStream { get; set; }
        public virtual User User { get; set; }
    }
}
